### ISSUE TITLE
Fill in abilities

### ISSUE THREAD

**Issue by xandrew** [darabos/alasala#115]

**Comment by darabos** [comment]
One more thing: For my heroes I tied the abilities to levels. I think this may not be implemented for other heroes, but would be nice.

**Comment by xandrew** [comment]
I didn't touch levels for now, as I think this is closely related to balance. It's very easy to set minimum level to any Action and Ability, so it's a matter of deciding what makes sense from a balance POV.

**Comment by hannagabor** [comment]
Sure, we'll tweak them!
