### ISSUE TITLE
Unique heroes on frontend

### ISSUE THREAD

**Issue by darabos** [darabos/alasala#33]
The hero should have presentational attributes that the backend sends to the frontend (#32).
- Size.
- Color.
- Appendages?
- Sound?

**Comment by darabos** [comment]
We could also display this 3D model on the hero page if we have time.

**Comment by xandrew** [comment]
Most important one: weight! It will play super well in the animation.

**Comment by darabos** [comment]
Instead of hand-drawn portraits on the cards we can use the 3D avatars everywhere! Saves a ton of time!

**Comment by darabos** [comment]
We still have to make the individual models, but the general setup is there.
